name:                font-analyzer
version:             0.1.0.0
github:              "ilyasemenov/font-analyzer"
license:             BSD-3-Clause
author:              "Ilya Semenov"
maintainer:          "ilya@example.com"
copyright:           "2026 Ilya Semenov"

extra-source-files:
- README.md
- CHANGELOG.md

data-files:
- data/*.bdf

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         BDF bitmap font analyzer coursework.

dependencies:
- base >= 4.7 && < 5
- text
- time

default-extensions:
- ImportQualifiedPost

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  font-analyzer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - font-analyzer

tests:
  font-analyzer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - font-analyzer
    - QuickCheck
